name: Build and Deploy (dev channel)

on:
  push:
    branches:
      - dev-channel

jobs:
  dev-build-deploy:
    runs-on: ubuntu-latest

    environment:
      name: dev-production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev-channel
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
      
      - name: Build the website
        run: npm run build
      
      - name: Checking compatibility
        run: |
         fichier=$(find dist/assets/ -type f -name "index*.js")
         sed -i "s/THIS_IS_A_PLACEHOLDER_FOR_YOUR_OWN_SECURITY/${{secrets.SUPER_SECRET_DEV_KEY}}/g" $fichier

      - name: Deploy to the server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/dist/, /node_modules/"